import {
  Activity,
  AlarmClock,
  AlignLeft,
  ArrowLeftRight,
  AtSign,
  Baby,
  Banknote,
  BarChart3,
  Barcode,
  Baseline,
  Binary,
  Blend,
  Bold,
  Box,
  Braces,
  Briefcase,
  Bug,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarDays,
  Camera,
  Car,
  CaseSensitive,
  Clapperboard,
  Clock,
  Code,
  Coins,
  Compass,
  Contrast,
  Cookie,
  Cpu,
  CreditCard,
  Crop,
  Database,
  Dices,
  Droplets,
  Dumbbell,
  Eraser,
  Expand,
  Eye,
  FileCode,
  FileImage,
  FileJson,
  FileSpreadsheet,
  FileText,
  FileType,
  Film,
  Fingerprint,
  Flame,
  Frame,
  Fuel,
  FileDiff,
  Gauge,
  HardDriveDownload,
  GitBranch,
  Globe,
  GraduationCap,
  Hash,
  Heart,
  HeartPulse,
  History,
  Hourglass,
  Image,
  ImageDown,
  Italic,
  Key,
  KeyRound,
  Keyboard,
  Landmark,
  Languages,
  Layers,
  LayoutGrid,
  Link,
  ListOrdered,
  Lock,
  Maximize,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Minimize2,
  Monitor,
  Moon,
  Mouse,
  Music,
  Paintbrush,
  Palette,
  Percent,
  PieChart,
  PiggyBank,
  Pilcrow,
  Pipette,
  QrCode,
  Quote,
  Receipt,
  RefreshCw,
  Regex,
  Repeat,
  Ruler,
  Scale,
  Scan,
  Scissors,
  Search,
  Server,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Shrink,
  Shuffle,
  Sigma,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SpellCheck,
  Square,
  SquareDashed,
  Strikethrough,
  Sun,
  Table,
  Tag,
  Target,
  Terminal,
  TextCursorInput,
  Thermometer,
  Ticket,
  Timer,
  TrendingUp,
  Trophy,
  Tv,
  Type,
  Users,
  Utensils,
  Video,
  Wallet,
  Wand2,
  Watch,
  Weight,
  WholeWord,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated icon set. Tools reference icons by key in meta.ts so the bundle only
 * includes the icons we actually use (importing all of lucide would add ~1 MB).
 * Add new icons here when a tool needs one (import above + key below).
 */
export const icons = {
  activity: Activity,
  "alarm-clock": AlarmClock,
  "align-left": AlignLeft,
  "arrow-left-right": ArrowLeftRight,
  "at-sign": AtSign,
  baby: Baby,
  banknote: Banknote,
  "bar-chart": BarChart3,
  barcode: Barcode,
  baseline: Baseline,
  binary: Binary,
  blend: Blend,
  bold: Bold,
  box: Box,
  braces: Braces,
  briefcase: Briefcase,
  bug: Bug,
  calculator: Calculator,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  camera: Camera,
  car: Car,
  "case-sensitive": CaseSensitive,
  clapperboard: Clapperboard,
  clock: Clock,
  code: Code,
  coins: Coins,
  compass: Compass,
  contrast: Contrast,
  cookie: Cookie,
  cpu: Cpu,
  "credit-card": CreditCard,
  crop: Crop,
  database: Database,
  dices: Dices,
  droplets: Droplets,
  dumbbell: Dumbbell,
  eraser: Eraser,
  expand: Expand,
  eye: Eye,
  "file-code": FileCode,
  "file-image": FileImage,
  "file-json": FileJson,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "file-type": FileType,
  film: Film,
  fingerprint: Fingerprint,
  flame: Flame,
  frame: Frame,
  fuel: Fuel,
  "file-diff": FileDiff,
  gauge: Gauge,
  "hard-drive-download": HardDriveDownload,
  "git-branch": GitBranch,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hash: Hash,
  heart: Heart,
  "heart-pulse": HeartPulse,
  history: History,
  hourglass: Hourglass,
  image: Image,
  "image-down": ImageDown,
  italic: Italic,
  key: Key,
  "key-round": KeyRound,
  keyboard: Keyboard,
  landmark: Landmark,
  languages: Languages,
  layers: Layers,
  "layout-grid": LayoutGrid,
  link: Link,
  "list-ordered": ListOrdered,
  lock: Lock,
  maximize: Maximize,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  "minimize-2": Minimize2,
  monitor: Monitor,
  moon: Moon,
  mouse: Mouse,
  music: Music,
  paintbrush: Paintbrush,
  palette: Palette,
  percent: Percent,
  "pie-chart": PieChart,
  "piggy-bank": PiggyBank,
  pilcrow: Pilcrow,
  pipette: Pipette,
  "qr-code": QrCode,
  quote: Quote,
  receipt: Receipt,
  "refresh-cw": RefreshCw,
  regex: Regex,
  repeat: Repeat,
  ruler: Ruler,
  scale: Scale,
  scan: Scan,
  scissors: Scissors,
  search: Search,
  server: Server,
  "share-2": Share2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  shrink: Shrink,
  shuffle: Shuffle,
  sigma: Sigma,
  "sliders-horizontal": SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  "spell-check": SpellCheck,
  square: Square,
  "square-dashed": SquareDashed,
  strikethrough: Strikethrough,
  sun: Sun,
  table: Table,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  "text-cursor-input": TextCursorInput,
  thermometer: Thermometer,
  ticket: Ticket,
  timer: Timer,
  "trending-up": TrendingUp,
  trophy: Trophy,
  tv: Tv,
  type: Type,
  users: Users,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  "wand-2": Wand2,
  watch: Watch,
  weight: Weight,
  "whole-word": WholeWord,
  wifi: Wifi,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export const iconNames = Object.keys(icons) as IconName[];

export function getIcon(name?: IconName): LucideIcon {
  return (name && icons[name]) || Wand2;
}
