/**
 * Reference passage used to estimate words per page when the visitor types a
 * word count instead of pasting text.
 *
 * It is ordinary English prose in six paragraphs of roughly 110 to 120 words,
 * which is close to how a student essay or a magazine article is broken up. It
 * mixes plain and more formal writing and averages about 5 letters per word. The calculator lays this
 * passage out repeatedly with the chosen typeface, margins and spacing and
 * divides the words by the pages it fills. Conversational text with shorter
 * words fits more words on a page; dense technical text fits fewer.
 */
export const REFERENCE_PARAGRAPHS: readonly string[] = [
  "A community garden usually begins with a single vacant lot and a handful of neighbors who are tired of looking at weeds. Someone brings a shovel, someone else brings a hose, and within a season the plot is divided into narrow beds marked with painted stakes. The first harvest is modest, mostly lettuce, radishes and a few crooked carrots, but it changes how people talk to each other. Strangers trade seeds over the fence. Children learn that tomatoes do not start life in a supermarket. Older residents who once felt invisible find that their knowledge of soil and weather is suddenly in demand, and the garden becomes a place where the block has a reason to gather.",
  "Public libraries occupy an unusual place in civic life. They are among the few institutions that welcome everyone without asking for payment, identification or a reason, and they have done so for well over a century. What began in the nineteenth century as a modest experiment in self-improvement, funded by wealthy donors and local subscriptions, has grown into a network of buildings that shelter readers, job seekers, immigrants, students and retirees under the same roof. The collection of books remains the foundation, but it is no longer the whole story. Today a branch may offer language classes, tax assistance, meeting rooms and quiet study space, all supported by the simple idea that access to information should not depend on income.",
  "Funding is usually smaller than people imagine. Most gardens survive on membership fees of a few dollars a month, plant sales, and the occasional small grant from a local foundation. Bulk soil and compost are the biggest expenses, followed by lumber for raised beds and the annual water bill. Volunteers who keep a simple ledger, even a notebook kept in the shed, find it much easier to apply for support because they can show exactly where earlier money went. Donated materials help, but they also come with strings, such as treated wood that should not touch edible plants, so it pays to ask questions before accepting a free truckload of anything.",
  "Staffing deserves more attention than it usually receives. A library is only as good as the people who run it, and the profession now asks far more of its workers than it did a generation ago. Staff members act as researchers, teachers, technical support and, occasionally, informal social workers for visitors facing difficult circumstances. Training has improved, but salaries have not kept pace with the growth in responsibility, and many experienced employees leave for better paid positions in the private sector. Communities that want strong libraries must be willing to pay for skilled staff, because no collection, however impressive, can replace a knowledgeable person who takes the time to understand what a visitor really needs.",
  "The growing itself rewards patience. Beginners tend to plant too much too soon, crowd their seedlings, and water a little every day instead of soaking the ground twice a week. Experienced members recommend starting with five or six reliable crops, such as beans, kale, zucchini and herbs, and adding one new experiment each year. Mulch keeps moisture in and weeds down, and a thin layer of compost in spring does more good than any bottled fertilizer. Pests are best handled early and by hand, with a bucket of soapy water for beetles and a row cover for the plants that matter most. Failure is normal, and a ruined crop of cabbage teaches more than a perfect crop of anything easy.",
  "Looking ahead, the future of public libraries will probably depend on how well they adapt without abandoning their founding principles. The institutions that thrive are likely to be those that listen carefully to their communities, measure success by usefulness rather than circulation figures alone, and remain open to anyone who walks through the door. Change will not always be comfortable, and disagreements about priorities are inevitable. Even so, the basic promise has proved remarkably durable: a shared space, freely available, where curiosity is treated as a public good. That promise is worth protecting, and the evidence of the past century suggests that communities which invest in it are rewarded many times over.",
];
