/**
 * Generates src/lib/tools/registry.generated.ts from the folders in src/tools.
 *
 * Every tool lives in its own folder:
 *   src/tools/<slug>/meta.ts     – exports `meta: ToolMeta`
 *   src/tools/<slug>/content.md  – long-form article (markdown)
 *   src/tools/<slug>/Tool.tsx    – client component, default export
 *
 * Adding a tool therefore never touches a shared file; this script wires it up.
 * Runs automatically before `dev` and `build` (see package.json).
 */
import { readdirSync, statSync, existsSync, writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const root = process.cwd();
const toolsDir = join(root, "src", "tools");
const outFile = join(root, "src", "lib", "tools", "registry.generated.ts");
const outClientFile = join(root, "src", "lib", "tools", "registry.client.generated.tsx");

function toIdentifier(slug: string): string {
  const id = slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()).replace(/[^a-zA-Z0-9_]/g, "");
  return /^[0-9]/.test(id) ? `t${id}` : id;
}

function listToolSlugs(): string[] {
  if (!existsSync(toolsDir)) return [];
  return readdirSync(toolsDir)
    .filter((name) => !name.startsWith("_") && !name.startsWith("."))
    .filter((name) => statSync(join(toolsDir, name)).isDirectory())
    .filter((name) => existsSync(join(toolsDir, name, "meta.ts")) && existsSync(join(toolsDir, name, "Tool.tsx")))
    .sort();
}

function writeIfChanged(file: string, content: string): boolean {
  mkdirSync(dirname(file), { recursive: true });
  if (existsSync(file) && readFileSync(file, "utf8") === content) return false;
  writeFileSync(file, content);
  return true;
}

const slugs = listToolSlugs();

const header = `// AUTO-GENERATED by scripts/generate-registry.ts – DO NOT EDIT.
// Run \`npm run gen\` after adding or removing a tool folder.
`;

const server = `${header}
import type { ToolMeta } from "./types";
${slugs.map((s) => `import { meta as ${toIdentifier(s)} } from "@/tools/${s}/meta";`).join("\n")}

export const toolMetas: ToolMeta[] = [
${slugs.map((s) => `  ${toIdentifier(s)},`).join("\n")}
];

export const toolSlugs = [
${slugs.map((s) => `  "${s}",`).join("\n")}
] as const;
`;

const client = `${header}
"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import { ToolSkeleton } from "@/components/tools/ToolSkeleton";

const loading = () => <ToolSkeleton />;

export const toolComponents: Record<string, ComponentType> = {
${slugs.map((s) => `  "${s}": dynamic(() => import("@/tools/${s}/Tool"), { loading }),`).join("\n")}
};
`;

const changedServer = writeIfChanged(outFile, server);
const changedClient = writeIfChanged(outClientFile, client);

console.log(
  `[gen] ${slugs.length} tool${slugs.length === 1 ? "" : "s"} registered` +
    (changedServer || changedClient ? " (registry updated)" : " (no changes)"),
);
